config/routes.rb
Rails.application.routes.draw do
  get 'ripon/lk'

     root 'pages#home'
     resource:articles
     get 'about', to:'pages#about'

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

def new
@article = Article.new
end
    
def create
@article=Article.new(article_params)
if @article.save
flash[:notice] = "Article was successfully created"
redirect_to article_path(@article)
else
render 'new'
end
end

 
private
def article_params
params.require(:article).permit(:title, :description)
end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
   def home
       
   end 
    def about
       
     end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/ripon_helper.rb
module RiponHelper
end

app/views/articles/new.html.erb
<h1>Create an article</h1>
<%= form_for @article do |f| %>
<p>
<%= f.label :title %><br/>
<%= f.text_field :title %>
</p>
<p>
<%= f.label :description %><br/>
<%= f.text_area :description %>
</p>
<p>
<%= f.submit %>
</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<h1>About page</h1>

<%= link_to 'Home', root_path %>

app/views/pages/home.html.erb
<h1>Welcome to my page</h1>

<%= link_to 'About', about_path %>